/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.kj133.action;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.kj133.entity.FleeHelp;
import com.kj133.entity.MapAdd;
import com.kj133.entity.bo.FleeHelpBO;

/** 
 * MyEclipse Struts
 * Creation date: 02-27-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class FleeHelpAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		    FleeHelpBO bo=new FleeHelpBO();
		    DynaActionForm dy=(DynaActionForm)form;
		    try{
		    	 MapAdd map=(MapAdd)dy.get("mapadd");//把上次的修改数据清空
		    	 map.setId("");
		    	 map.setInfo("");
		    	 
		    	 List list=bo.getMaxId();
		    	 FleeHelp help=(FleeHelp)list.get(0);
		    	 request.setAttribute("heloBean", help);
		    }catch(Exception e){
		    	e.printStackTrace();
		    }
		    return mapping.findForward("init");
	}
	
	
	/**
	 * 
	 * @param mapping
	 * @param form
	 * @param request  
	 * @param response
	 * @return  显示图片
	 */
	public ActionForward show(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		    FleeHelpBO bo=new FleeHelpBO();
		    try{
		    	 List list=bo.getMaxId();
		    	 FleeHelp help=(FleeHelp)list.get(0);
		         if(help.getMapdata() != null){
		        	 InputStream inputStream =help.getCompressdata().getBinaryStream();
		        	 OutputStream fileOutputStream =response.getOutputStream();
		        	 byte[] buf = new byte[1];
						int len = 0;
						while((len = inputStream.read(buf)) != -1) {
						    fileOutputStream.write(buf, 0, len);
						}
						inputStream.close();
						fileOutputStream.close();
		         }
		    }catch(Exception e){
		    	e.printStackTrace();
		    }
		   return  null;
	}
	
	
	/**
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return 修改
	 */
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		    FleeHelpBO bo=new FleeHelpBO();
		    DynaActionForm dy=(DynaActionForm)form;
		    try{
		    	  MapAdd map=(MapAdd)dy.get("mapadd");
		    	  FormFile file=map.getFile();
		    	  if( file!= null && !file.equals("")){
		    		  bo.saveMap(map);
		    	  }
		          bo.update(map);
		          
		    }catch(Exception e){
		    	e.printStackTrace();
		    }
		    return  mapping.findForward("update");
	}
	
	
}