<%@ page language="java" pageEncoding="UTF-8"%>
<%@ page info="显示地图" %>
<%@ taglib uri="http://struts.apache.org/tags-bean" prefix="bean" %>
<%@ taglib uri="http://struts.apache.org/tags-html" prefix="html" %>
<%@ taglib uri="http://struts.apache.org/tags-logic" prefix="logic" %>
<%@ taglib uri="http://struts.apache.org/tags-tiles" prefix="tiles" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html:html lang="true">
  <head>
    <html:base />
    <title>showMap.jsp</title>
<jsp:include flush="true" page="/checkUser.jsp"></jsp:include>
     <meta   http-equiv="refresh"  content="15" url="showMaP.do" /> 
  </head>
  
   <body bgColor="white" background="Image/right.gif"  style="overflow-x: hidden"> 
		<table width="796"  height="470" border="1">
			<tr>
			    <td height="471" background="images/hb.JPG">
			      <table  width="796"  height="470"  border="0" style="border-collapse:collapse;TABLE-LAYOUT:   fixed;   FONT-SIZE:   13px;">
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td align="center" colspan="17" ><font color="red" size="4">&nbsp;煤&nbsp;矿&nbsp;人&nbsp;员&nbsp;定&nbsp;位&nbsp;系&nbsp;统&nbsp;简&nbsp;图&nbsp;</font></td>
			             
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="right"><font color="red">127 (<%=  request.getAttribute("c14")%>人)</font></td>
			          </tr>
			          <tr>
			             <td colspan="2" align="left"><font color="red">&nbsp;3 (<%=  request.getAttribute("c3")%>人)</font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="left"><font color="red">13 (<%=  request.getAttribute("c13")%>人)</font></td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="left"><font color="red">2 (<%=  request.getAttribute("c2")%>人)</font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="left"><font color="red">1 (<%=  request.getAttribute("c1")%>人)</font></td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="left"><font color="red">4 (<%=  request.getAttribute("c4")%>人)</font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			            
			             <td colspan="2" align="left"><font color="red">12 (<%=  request.getAttribute("c12")%>人)</font></td>
			             <td>&nbsp;</td>
			              <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="left"><font color="red">9 (<%=  request.getAttribute("c9")%>人)</font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td colspan="2" align="left"><font color="red">&nbsp;5 (<%=  request.getAttribute("c5")%>人)</font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="right"><font color="red">&nbsp;8 (<%=  request.getAttribute("c8")%>人)</font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="right"><font color="red">&nbsp;11 (<%=  request.getAttribute("c11")%>人)</font></td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="left"><font color="red">6 (<%=  request.getAttribute("c6")%>人)</font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="left"><font color="red">10 (<%=  request.getAttribute("c10")%>人)</font></td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td colspan="2" align="left"><font color="red">7 (<%=  request.getAttribute("c7")%>人)</font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td colspan="3" align="left" ><font color="#FF0000" size="3" >井下总人数：<%= request.getAttribute("downCount") %></font></td>
			             <td colspan="3" align="right" ><font color="#FF0000" size="3" >井上总人数：<%= request.getAttribute("upCount") %></font></td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			          <tr>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			             <td>&nbsp;</td>
			          </tr>
			      </table>
			    </td> 
			</tr>
		</table>
  </body>
</html:html>
